// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: EmuServerDevEvent.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
using System.Text;

namespace MQtest
{

    [global::ProtoBuf.ProtoContract()]
    public partial class CEmuPicUrl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"vehicle_pic_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VehiclePicUrl
        {
            get { return __pbn__VehiclePicUrl ?? ""; }
            set { __pbn__VehiclePicUrl = value; }
        }
        public bool ShouldSerializeVehiclePicUrl() => __pbn__VehiclePicUrl != null;
        public void ResetVehiclePicUrl() => __pbn__VehiclePicUrl = null;
        private string __pbn__VehiclePicUrl;

        [global::ProtoBuf.ProtoMember(2, Name = @"plate_pic_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlatePicUrl
        {
            get { return __pbn__PlatePicUrl ?? ""; }
            set { __pbn__PlatePicUrl = value; }
        }
        public bool ShouldSerializePlatePicUrl() => __pbn__PlatePicUrl != null;
        public void ResetPlatePicUrl() => __pbn__PlatePicUrl = null;
        private string __pbn__PlatePicUrl;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CEmuRlsResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"release_auth", IsRequired = true)]
        public int ReleaseAuth { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"release_result", IsRequired = true)]
        public int ReleaseResult { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CEmuInResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rls_result", IsRequired = true)]
        public CEmuRlsResult RlsResult { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CEmuOutResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"rls_result", IsRequired = true)]
        public CEmuRlsResult RlsResult { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"total_cost")]
        public float TotalCost
        {
            get { return __pbn__TotalCost.GetValueOrDefault(); }
            set { __pbn__TotalCost = value; }
        }
        public bool ShouldSerializeTotalCost() => __pbn__TotalCost != null;
        public void ResetTotalCost() => __pbn__TotalCost = null;
        private float? __pbn__TotalCost;

        [global::ProtoBuf.ProtoMember(3, Name = @"real_cost")]
        public float RealCost
        {
            get { return __pbn__RealCost.GetValueOrDefault(); }
            set { __pbn__RealCost = value; }
        }
        public bool ShouldSerializeRealCost() => __pbn__RealCost != null;
        public void ResetRealCost() => __pbn__RealCost = null;
        private float? __pbn__RealCost;

        [global::ProtoBuf.ProtoMember(4, Name = @"charge_index")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ChargeIndex
        {
            get { return __pbn__ChargeIndex ?? ""; }
            set { __pbn__ChargeIndex = value; }
        }
        public bool ShouldSerializeChargeIndex() => __pbn__ChargeIndex != null;
        public void ResetChargeIndex() => __pbn__ChargeIndex = null;
        private string __pbn__ChargeIndex;

        [global::ProtoBuf.ProtoMember(5, Name = @"toller_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TollerId
        {
            get { return __pbn__TollerId ?? ""; }
            set { __pbn__TollerId = value; }
        }
        public bool ShouldSerializeTollerId() => __pbn__TollerId != null;
        public void ResetTollerId() => __pbn__TollerId = null;
        private string __pbn__TollerId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CEmuEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_cmd", IsRequired = true)]
        public int EventCmd { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"park_name", IsRequired = true)]
        public string ParkName { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"park_index", IsRequired = true)]
        public string ParkIndex { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"gate_name", IsRequired = true)]
        public string GateName { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"gate_index", IsRequired = true)]
        public string GateIndex { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"roadway_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RoadwayName
        {
            get { return __pbn__RoadwayName ?? ""; }
            set { __pbn__RoadwayName = value; }
        }
        public bool ShouldSerializeRoadwayName() => __pbn__RoadwayName != null;
        public void ResetRoadwayName() => __pbn__RoadwayName = null;
        private string __pbn__RoadwayName;

        [global::ProtoBuf.ProtoMember(7, Name = @"roadway_index")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RoadwayIndex
        {
            get { return __pbn__RoadwayIndex ?? ""; }
            set { __pbn__RoadwayIndex = value; }
        }
        public bool ShouldSerializeRoadwayIndex() => __pbn__RoadwayIndex != null;
        public void ResetRoadwayIndex() => __pbn__RoadwayIndex = null;
        private string __pbn__RoadwayIndex;

        [global::ProtoBuf.ProtoMember(8, Name = @"vehicle_type")]
        public int VehicleType
        {
            get { return __pbn__VehicleType.GetValueOrDefault(); }
            set { __pbn__VehicleType = value; }
        }
        public bool ShouldSerializeVehicleType() => __pbn__VehicleType != null;
        public void ResetVehicleType() => __pbn__VehicleType = null;
        private int? __pbn__VehicleType;

        [global::ProtoBuf.ProtoMember(9, Name = @"plate_type")]
        public int PlateType
        {
            get { return __pbn__PlateType.GetValueOrDefault(); }
            set { __pbn__PlateType = value; }
        }
        public bool ShouldSerializePlateType() => __pbn__PlateType != null;
        public void ResetPlateType() => __pbn__PlateType = null;
        private int? __pbn__PlateType;

        [global::ProtoBuf.ProtoMember(10, Name = @"vehicle_color")]
        public int VehicleColor
        {
            get { return __pbn__VehicleColor.GetValueOrDefault(); }
            set { __pbn__VehicleColor = value; }
        }
        public bool ShouldSerializeVehicleColor() => __pbn__VehicleColor != null;
        public void ResetVehicleColor() => __pbn__VehicleColor = null;
        private int? __pbn__VehicleColor;

        [global::ProtoBuf.ProtoMember(11, Name = @"plate_color")]
        public int PlateColor
        {
            get { return __pbn__PlateColor.GetValueOrDefault(); }
            set { __pbn__PlateColor = value; }
        }
        public bool ShouldSerializePlateColor() => __pbn__PlateColor != null;
        public void ResetPlateColor() => __pbn__PlateColor = null;
        private int? __pbn__PlateColor;

        [global::ProtoBuf.ProtoMember(12, Name = @"plate_no")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlateNo
        {
            get { return __pbn__PlateNo ?? ""; }
            set { __pbn__PlateNo = value; }
        }
        public bool ShouldSerializePlateNo() => __pbn__PlateNo != null;
        public void ResetPlateNo() => __pbn__PlateNo = null;
        private string __pbn__PlateNo;

        [global::ProtoBuf.ProtoMember(13, Name = @"card_no")]
        [global::System.ComponentModel.DefaultValue("")]
        public string CardNo
        {
            get { return __pbn__CardNo ?? ""; }
            set { __pbn__CardNo = value; }
        }
        public bool ShouldSerializeCardNo() => __pbn__CardNo != null;
        public void ResetCardNo() => __pbn__CardNo = null;
        private string __pbn__CardNo;

        [global::ProtoBuf.ProtoMember(14, Name = @"event_index")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EventIndex
        {
            get { return __pbn__EventIndex ?? ""; }
            set { __pbn__EventIndex = value; }
        }
        public bool ShouldSerializeEventIndex() => __pbn__EventIndex != null;
        public void ResetEventIndex() => __pbn__EventIndex = null;
        private string __pbn__EventIndex;

        [global::ProtoBuf.ProtoMember(15, Name = @"roadway_type")]
        public int RoadwayType
        {
            get { return __pbn__RoadwayType.GetValueOrDefault(); }
            set { __pbn__RoadwayType = value; }
        }
        public bool ShouldSerializeRoadwayType() => __pbn__RoadwayType != null;
        public void ResetRoadwayType() => __pbn__RoadwayType = null;
        private int? __pbn__RoadwayType;

        [global::ProtoBuf.ProtoMember(16, Name = @"main_logo")]
        public int MainLogo
        {
            get { return __pbn__MainLogo.GetValueOrDefault(); }
            set { __pbn__MainLogo = value; }
        }
        public bool ShouldSerializeMainLogo() => __pbn__MainLogo != null;
        public void ResetMainLogo() => __pbn__MainLogo = null;
        private int? __pbn__MainLogo;

        [global::ProtoBuf.ProtoMember(17, Name = @"sub_logo")]
        public int SubLogo
        {
            get { return __pbn__SubLogo.GetValueOrDefault(); }
            set { __pbn__SubLogo = value; }
        }
        public bool ShouldSerializeSubLogo() => __pbn__SubLogo != null;
        public void ResetSubLogo() => __pbn__SubLogo = null;
        private int? __pbn__SubLogo;

        [global::ProtoBuf.ProtoMember(18, Name = @"sub_model")]
        public int SubModel
        {
            get { return __pbn__SubModel.GetValueOrDefault(); }
            set { __pbn__SubModel = value; }
        }
        public bool ShouldSerializeSubModel() => __pbn__SubModel != null;
        public void ResetSubModel() => __pbn__SubModel = null;
        private int? __pbn__SubModel;

        [global::ProtoBuf.ProtoMember(19, Name = @"plate_believe")]
        public int PlateBelieve
        {
            get { return __pbn__PlateBelieve.GetValueOrDefault(); }
            set { __pbn__PlateBelieve = value; }
        }
        public bool ShouldSerializePlateBelieve() => __pbn__PlateBelieve != null;
        public void ResetPlateBelieve() => __pbn__PlateBelieve = null;
        private int? __pbn__PlateBelieve;

        [global::ProtoBuf.ProtoMember(20, Name = @"alarm_car")]
        public int AlarmCar
        {
            get { return __pbn__AlarmCar.GetValueOrDefault(); }
            set { __pbn__AlarmCar = value; }
        }
        public bool ShouldSerializeAlarmCar() => __pbn__AlarmCar != null;
        public void ResetAlarmCar() => __pbn__AlarmCar = null;
        private int? __pbn__AlarmCar;

        [global::ProtoBuf.ProtoMember(30, Name = @"pic_url")]
        public CEmuPicUrl PicUrl { get; set; }

        [global::ProtoBuf.ProtoMember(31, Name = @"in_result")]
        public CEmuInResult InResult { get; set; }

        [global::ProtoBuf.ProtoMember(32, Name = @"out_result")]
        public CEmuOutResult OutResult { get; set; }

        public string EmuEventToString()
        {
            StringBuilder eventToStrBuilder = new StringBuilder();
            eventToStrBuilder.Append("EventCmd:" + this.EventCmd.ToString()).Append("\r\n");
            //停车场名称
            eventToStrBuilder.Append("ParkName:" + this.ParkName).Append("\r\n");
            eventToStrBuilder.Append("ParkIndex:" + this.ParkIndex).Append("\r\n");
            //出入口名称
            eventToStrBuilder.Append("GateName:" + this.GateName).Append("\r\n");
            eventToStrBuilder.Append("GateIndex:" + this.GateIndex).Append("\r\n");
            //车道名称
            eventToStrBuilder.Append("RoadwayName:" + this.RoadwayName).Append("\r\n");
            eventToStrBuilder.Append("RoadwayIndex:" + this.RoadwayIndex).Append("\r\n");

            //车辆类型，0-其他车辆，1-小型车，2-大型车
            eventToStrBuilder.Append("VehicleType:" + this.VehicleType.ToString()).Append("\r\n");
            //车牌类型,0-标准民用车与军车车牌,1-02式民用车牌,2-武警车车牌,3-警车车牌,4-民用车双行尾牌,5-使馆车牌,6-农用车车牌
            eventToStrBuilder.Append("PlateType:" + this.PlateType.ToString()).Append("\r\n");
            //车辆颜色,0-其它颜色,1-白色,2-银色,3-灰色,4-黑色,5-红色,6-深蓝,7-蓝色,8-黄色,9-绿色,10-棕色,11-粉色,12-紫色
            eventToStrBuilder.Append("VehicleColor:" + this.VehicleColor.ToString()).Append("\r\n");
            //车牌颜色,0-蓝色,1-黄色,2-白色,3-黑色,4-绿色,5-民航黑色,0xff-其它
            eventToStrBuilder.Append("PlateColor:" + this.PlateColor.ToString()).Append("\r\n");
            //车牌号
            eventToStrBuilder.Append("PlateNo:" + this.PlateNo).Append("\r\n");
            eventToStrBuilder.Append("CardNo:" + this.CardNo).Append("\r\n");
            eventToStrBuilder.Append("EventIndex:" + this.EventIndex).Append("\r\n");
            //车道类型,0-入口,1-出口不收费,2-出口岗亭收费,3-出口中央收费
            eventToStrBuilder.Append("RoadwayType:" + this.RoadwayType.ToString()).Append("\r\n");

            //是否为黑名单车辆,0-否,1-是
            eventToStrBuilder.Append("AlarmCar:" + this.AlarmCar.ToString()).Append("\r\n");

            //图片URL信息，event_cmd为2时解析该字段
            if (this.EventCmd == 2)
            {
                //车辆图片URL
                eventToStrBuilder.Append("VehiclePicUrl:" + this.PicUrl.VehiclePicUrl).Append("\r\n");
                //车牌图片URL
                eventToStrBuilder.Append("PlatePicUrl:" + this.PicUrl.PlatePicUrl).Append("\r\n");
            }

            //进场结果，event_cmd为3时解析该字段
            if (this.EventCmd == 3)
            {
                //放行权限
                eventToStrBuilder.Append("ReleaseAuth:" + this.InResult.RlsResult.ReleaseAuth.ToString()).Append("\r\n");
                //放行结果
                eventToStrBuilder.Append("ReleaseResult:" + this.InResult.RlsResult.ReleaseResult.ToString()).Append("\r\n");
            }

            //出场结果，event_cmd为4时解析该字段
            if (this.EventCmd == 4)
            {
                //放行权限
                eventToStrBuilder.Append("ReleaseAuth:" + this.OutResult.RlsResult.ReleaseAuth.ToString()).Append("\r\n");
                //放行结果
                eventToStrBuilder.Append("ReleaseResult:" + this.OutResult.RlsResult.ReleaseResult.ToString()).Append("\r\n");
                //出场应收金额
                eventToStrBuilder.Append("TotalCost:" + this.OutResult.TotalCost.ToString()).Append("\r\n");
                //出场实收金额
                eventToStrBuilder.Append("RealCost:" + this.OutResult.RealCost.ToString()).Append("\r\n");
                //账单编号
                eventToStrBuilder.Append("ChargeIndex:" + this.OutResult.ChargeIndex).Append("\r\n");
                //收费员ID
                eventToStrBuilder.Append("TollerId:" + this.OutResult.TollerId).Append("\r\n");

            }

            return eventToStrBuilder.ToString();
        }
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CEmuSendEventInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_index", IsRequired = true)]
        public string EventIndex { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"event_type", IsRequired = true)]
        public int EventType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"event_state", IsRequired = true)]
        public int EventState { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"device_index", IsRequired = true)]
        public string DeviceIndex { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"sub_dev_index")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SubDevIndex
        {
            get { return __pbn__SubDevIndex ?? ""; }
            set { __pbn__SubDevIndex = value; }
        }
        public bool ShouldSerializeSubDevIndex() => __pbn__SubDevIndex != null;
        public void ResetSubDevIndex() => __pbn__SubDevIndex = null;
        private string __pbn__SubDevIndex;

        [global::ProtoBuf.ProtoMember(6, Name = @"device_model")]
        public int DeviceModel
        {
            get { return __pbn__DeviceModel.GetValueOrDefault(); }
            set { __pbn__DeviceModel = value; }
        }
        public bool ShouldSerializeDeviceModel() => __pbn__DeviceModel != null;
        public void ResetDeviceModel() => __pbn__DeviceModel = null;
        private int? __pbn__DeviceModel;

        [global::ProtoBuf.ProtoMember(7, Name = @"time", IsRequired = true)]
        public string Time { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"event_info", IsRequired = true)]
        public CEmuEvent EventInfo { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"vehicle_pic_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VehiclePicPath
        {
            get { return __pbn__VehiclePicPath ?? ""; }
            set { __pbn__VehiclePicPath = value; }
        }
        public bool ShouldSerializeVehiclePicPath() => __pbn__VehiclePicPath != null;
        public void ResetVehiclePicPath() => __pbn__VehiclePicPath = null;
        private string __pbn__VehiclePicPath;

        [global::ProtoBuf.ProtoMember(10, Name = @"plate_pic_path")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlatePicPath
        {
            get { return __pbn__PlatePicPath ?? ""; }
            set { __pbn__PlatePicPath = value; }
        }
        public bool ShouldSerializePlatePicPath() => __pbn__PlatePicPath != null;
        public void ResetPlatePicPath() => __pbn__PlatePicPath = null;
        private string __pbn__PlatePicPath;

        [global::ProtoBuf.ProtoMember(20, Name = @"event_id")]
        public long EventId
        {
            get { return __pbn__EventId.GetValueOrDefault(); }
            set { __pbn__EventId = value; }
        }
        public bool ShouldSerializeEventId() => __pbn__EventId != null;
        public void ResetEventId() => __pbn__EventId = null;
        private long? __pbn__EventId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CPlaceEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"event_type", IsRequired = true)]
        public int EventType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"parking_id", IsRequired = true)]
        public int ParkingId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"floor_id", IsRequired = true)]
        public int FloorId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"camera_id", IsRequired = true)]
        public int CameraId { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"place_id", IsRequired = true)]
        public int PlaceId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"parking_syscode", IsRequired = true)]
        public string ParkingSyscode { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"floor_syscode", IsRequired = true)]
        public string FloorSyscode { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"place_syscode", IsRequired = true)]
        public string PlaceSyscode { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"camera_syscode", IsRequired = true)]
        public string CameraSyscode { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"event_time", IsRequired = true)]
        public string EventTime { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"event_syscode", IsRequired = true)]
        public string EventSyscode { get; set; }

        [global::ProtoBuf.ProtoMember(20, Name = @"plate_no")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlateNo
        {
            get { return __pbn__PlateNo ?? ""; }
            set { __pbn__PlateNo = value; }
        }
        public bool ShouldSerializePlateNo() => __pbn__PlateNo != null;
        public void ResetPlateNo() => __pbn__PlateNo = null;
        private string __pbn__PlateNo;

        [global::ProtoBuf.ProtoMember(21, Name = @"pic_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PicUrl
        {
            get { return __pbn__PicUrl ?? ""; }
            set { __pbn__PicUrl = value; }
        }
        public bool ShouldSerializePicUrl() => __pbn__PicUrl != null;
        public void ResetPicUrl() => __pbn__PicUrl = null;
        private string __pbn__PicUrl;

        [global::ProtoBuf.ProtoMember(22, Name = @"plate_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PlateUrl
        {
            get { return __pbn__PlateUrl ?? ""; }
            set { __pbn__PlateUrl = value; }
        }
        public bool ShouldSerializePlateUrl() => __pbn__PlateUrl != null;
        public void ResetPlateUrl() => __pbn__PlateUrl = null;
        private string __pbn__PlateUrl;

        [global::ProtoBuf.ProtoMember(23, Name = @"tpm_id")]
        public int TpmId
        {
            get { return __pbn__TpmId.GetValueOrDefault(); }
            set { __pbn__TpmId = value; }
        }
        public bool ShouldSerializeTpmId() => __pbn__TpmId != null;
        public void ResetTpmId() => __pbn__TpmId = null;
        private int? __pbn__TpmId;

        [global::ProtoBuf.ProtoMember(24, Name = @"tpm_syscode")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TpmSyscode
        {
            get { return __pbn__TpmSyscode ?? ""; }
            set { __pbn__TpmSyscode = value; }
        }
        public bool ShouldSerializeTpmSyscode() => __pbn__TpmSyscode != null;
        public void ResetTpmSyscode() => __pbn__TpmSyscode = null;
        private string __pbn__TpmSyscode;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum ParkSubsysEventType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_SUBSYS_EVENT_TYPE_IN")]
        ParkSubsysEventTypeIn = 524545,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_SUBSYS_EVENT_TYPE_OUT")]
        ParkSubsysEventTypeOut = 524546,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_SUBSYS_EVENT_TYPE_PLACE_ENTYR")]
        ParkSubsysEventTypePlaceEntyr = 524547,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_SUBSYS_EVENT_TYPE_PLACE_LEAVE")]
        ParkSubsysEventTypePlaceLeave = 524548,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ParkSubsysEventCmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_SUBSYS_EVENT_CMD_VEHICLE")]
        ParkSubsysEventCmdVehicle = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_SUBSYS_EVENT_CMD_URL")]
        ParkSubsysEventCmdUrl = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_SUBSYS_EVENT_CMD_IN_RESULT")]
        ParkSubsysEventCmdInResult = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_SUBSYS_EVENT_CMD_OUT_RESULT")]
        ParkSubsysEventCmdOutResult = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_SUBSYS_EVENT_CMD_MODIFY_PLATE")]
        ParkSubsysEventCmdModifyPlate = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ParkSubsysReleaseResult
    {
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_RELEASE_RESULT_FORBID")]
        ParkReleaseResultForbid = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_RELEASE_RESULT_VALIDITY")]
        ParkReleaseResultValidity = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_RELEASE_RESULT_IN_TEMP")]
        ParkReleaseResultInTemp = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_RELEASE_RESULT_OUT_OFFLINE")]
        ParkReleaseResultOutOffline = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_RELEASE_RESULT_OUT_CHARGE")]
        ParkReleaseResultOutCharge = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_RELEASE_RESULT_OUT_CHARGE_FRONT")]
        ParkReleaseResultOutChargeFront = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_RELEASE_RESULT_OUT_FREE")]
        ParkReleaseResultOutFree = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"PARK_RELEASE_RESULT_ILLEGAL_CARD")]
        ParkReleaseResultIllegalCard = 30,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
