// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: comm.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace MQtest
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TriggerResult : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"trigger_type", IsRequired = true)]
        public int TriggerType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"trigger_ret")]
        public int[] TriggerRets { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"trigger_time", IsRequired = true)]
        public string TriggerTime { get; set; }

        [global::ProtoBuf.ProtoMember(33, Name = @"trigger_info")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TriggerInfo
        {
            get { return __pbn__TriggerInfo ?? ""; }
            set { __pbn__TriggerInfo = value; }
        }
        public bool ShouldSerializeTriggerInfo() => __pbn__TriggerInfo != null;
        public void ResetTriggerInfo() => __pbn__TriggerInfo = null;
        private string __pbn__TriggerInfo;

        [global::ProtoBuf.ProtoMember(34, Name = @"err_msg")]
        [global::System.ComponentModel.DefaultValue("")]
        public string ErrMsg
        {
            get { return __pbn__ErrMsg ?? ""; }
            set { __pbn__ErrMsg = value; }
        }
        public bool ShouldSerializeErrMsg() => __pbn__ErrMsg != null;
        public void ResetErrMsg() => __pbn__ErrMsg = null;
        private string __pbn__ErrMsg;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CommEventTrig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"trigger_type", IsRequired = true)]
        public int TriggerType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"trigger_info", IsRequired = true)]
        public byte[] TriggerInfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum EventState
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EVENT_STATE_INSTANT")]
        EventStateInstant = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EVENT_STATE_START")]
        EventStateStart = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"EVENT_STATE_STOP")]
        EventStateStop = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"EVENT_STATE_PULSE")]
        EventStatePulse = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"EVENT_STATE_UPDATE")]
        EventStateUpdate = 4,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MsgCmdType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"MSG_CMD_TYPE_MASK")]
        MsgCmdTypeMask = 65280,
        [global::ProtoBuf.ProtoEnum(Name = @"MSG_CMD_MANUAL_EVENT")]
        MsgCmdManualEvent = 257,
        [global::ProtoBuf.ProtoEnum(Name = @"MSG_CMD_CONFIRM_EVENT")]
        MsgCmdConfirmEvent = 258,
        [global::ProtoBuf.ProtoEnum(Name = @"MSG_CMD_REPORT_EVENT")]
        MsgCmdReportEvent = 513,
        [global::ProtoBuf.ProtoEnum(Name = @"MSG_CMD_SUBRECV_EVENT")]
        MsgCmdSubrecvEvent = 514,
        [global::ProtoBuf.ProtoEnum(Name = @"MSG_CMD_EVENT_NOTIFY_REQ")]
        MsgCmdEventNotifyReq = 769,
        [global::ProtoBuf.ProtoEnum(Name = @"MSG_CMD_EVENT_NOTIFY_RSP")]
        MsgCmdEventNotifyRsp = 770,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
